### ISSUE TITLE
Pull out network cable - no way to recover

### ISSUE THREAD

**Issue by erolosty** [spring-projects/spring-integration-kafka#32] opened 2015-04-20 16:37 UTC
We want to be able to reconnect automatically if a network connection is dropped. When we use the Consumer it seems to spin up runnables into threads, but unfortunately in exceptional circumstances (such as disabling the network connection) - the ListenerContainer is left in a state were isRunning=true but the threads have bombed out, and .start() would need to be called to resume Consumption of messages - but with no way for client code to know that the ListenerContainer is no longer working, knowing that we should call start() is impossible

**Comment by garyrussell** [comment] 2015-04-20 18:30
Thanks for reporting this; I have confirmed that is an issue and have opened a [JIRA Issue](https://jira.spring.io/browse/INTEXT-165) which you can follow; we'll report back here, too, when the issue is resolved.

**Comment by erolosty** [comment] 2015-04-21 13:28
Much appreciated

**Comment by mbogoevici** [comment] 2015-05-31 12:39
This should be fixed now that we've addressed https://jira.spring.io/browse/INTEXT-165. 
Please give it another try and let us know if you're still having problems.
Thanks!

**Closed by mbogoevici** 2015-05-31 12:39 UTC
