### ISSUE TITLE
KafkaMessageDrivenChannelAdapter.IntegrationMessageListener should override handleListenerException()

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration-kafka#124] opened 2016-07-14 15:04 UTC
Currently, s-i-k simply eats exceptions instead of propagating them to the container.

**Comment by garyrussell** [comment] 2016-07-14 15:06
This is probably an issue for s-k `@KafkaListener` too.

**Comment by artembilan** [comment] 2016-07-14 15:55
Sorry, the issue isn't clear.
Need more background and sample to reproduce/play.

The `IntegrationMessageListener` has code:
```
@Override
public void onMessage(ConsumerRecord<K, V> record, Acknowledgment acknowledgment) {
	Message<?> message = toMessagingMessage(record, acknowledgment);
	sendMessage(message);
}
```
Where `sendMessage()` is a full delegation to SI `MessageProducerSupport` logic:
```
try {
	this.messagingTemplate.send(this.outputChannel, message);
}
catch (RuntimeException e) {
	if (this.errorChannel != null) {
		this.messagingTemplate.send(this.errorChannel, new ErrorMessage(e));
	}
	else  {
		throw e;
	}
}
```
So, maybe you should just configure that `errorChannel`?..
Although it isn't clear to me why SI Core still don't use there built-in `errorChannel` bean by default...

Or do you mean the problem with supper class `AbstractAdaptableMessageListener`:
```
public void onMessage(ConsumerRecord<K, V> record) {
	try {
		onMessage(record, null);
	}
	catch (Exception ex) {
		handleListenerException(ex);
	}
}

protected void handleListenerException(Throwable ex) {
	this.logger.error("Listener execution failed", ex);
}
```

Maybe default behavior must be *re-throw* into container directly:
```
try {
    // Invoke Listener
}
catch (Exception e) {
...
      if (this.containerProperties.getErrorHandler() != null) {
	     this.containerProperties.getErrorHandler().handle(e, record);
      }
      else {
	     this.logger.error("Listener threw an exception and no error handler for " + record, e);
      }
}
```
?

Then it is an issue of Spring Kafka, not SIK.

With that I guess the problem with `@KafkaListener` will gone silently as well.

CC @sobychacko

**Comment by sobychacko** [comment] 2016-07-14 16:15
Per Gary, the issue is that that the `IntegrationMessageListene`r in `KafkaMessageDrivenChannelAdapter` uses the default `handleListenerException` from `AbstractAdaptableMessageListener` which simply eats the exception. We need a way for the `IntegrationMessageListener` to rethrow exception back to the caller.

**Comment by artembilan** [comment] 2016-07-14 17:28
OK. After the further digging I see this.
`IntegrationMessageListener` being as `AcknowledgingMessageListener` as well is called from the `container` via:
```
if (this.acknowledgingMessageListener != null) {
	this.acknowledgingMessageListener.onMessage(record,
		new ConsumerAcknowledgment(record, this.isManualImmediateAck));
}
```
where we have an implementation as:
```
public void onMessage(ConsumerRecord<K, V> record, Acknowledgment acknowledgment) {
	Message<?> message = toMessagingMessage(record, acknowledgment);
	sendMessage(message);
}
```
so, that odd ` handleListenerException()` isn't reachable.
My test with the code like:
```
final CountDownLatch errorHandlerLatch = new CountDownLatch(1);
containerProps.setErrorHandler(new ErrorHandler() {

	@Override
	public void handle(Exception thrownException, ConsumerRecord<?, ?> record) {
		errorHandlerLatch.countDown();
	}

});
...
adapter.setOutputChannel(new FixedSubscriberChannel(new MessageHandler() {

	@Override
	public void handleMessage(Message<?> message) throws MessagingException {
		throw new RuntimeException("intentional");
	}

}));
...
template.sendDefault(1, "foo");

assertThat(errorHandlerLatch.await(10, TimeUnit.SECONDS)).isTrue();
```
confirms that an exception is re-thrown directly into the container.

What am I missing ?

**Comment by sobychacko** [comment] 2016-07-14 17:53
what happens if you try the same code, but without the `AcknowledgingMessageListener`?

**Comment by artembilan** [comment] 2016-07-14 17:54
??? I can't do that.
See `IntegrationMessageListener`  source code.

**Comment by sobychacko** [comment] 2016-07-14 17:55
ah - i see. ok. Lets wait for Garry to chime in then.

**Comment by garyrussell** [comment] 2016-07-15 10:32
Strange indeed. In skype, Soby provided this...

>2016-07-14 10:53:48,822 ERROR -kafka-listener-1 o.s.i.k.i.KafkaMessageDrivenChannelAdapter$IntegrationMessageListener:73 - Listener execution failed
org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'null'; nested exception is java.lang.RuntimeException

Which clearly means the listener is being invoked somehow via `onMessage(cr)` instead of `onMessage(cr, ack)`, which should not be possible since the `IntegrationMessageListener` is an acknowledging listener.

We should fix the adapter to propagate the exception to the container (I will open an issue over there) but we need to understand why that method is being called with a null ack.

Soby, can you share your project/branch?

Thanks

**Comment by garyrussell** [comment] 2016-07-15 10:36
That said, the `IntegrationMessageListener` doesn't really need to extend the adapter - we can simply implement `AcknowledgingMessageListener`.

**Comment by artembilan** [comment] 2016-07-15 13:36
Indeed, that message we have only in the:
```
protected void handleListenerException(Throwable ex) {
	this.logger.error("Listener execution failed", ex);
}
```
So, it isn't clear how an `IntegrationMessageListener` is used from the container not as `AcknowledgingMessageListener`.
Although the log line number isn't clear to me as well:
```
2016-07-14 10:53:48,822 ERROR -kafka-listener-1 o.s.i.k.i.KafkaMessageDrivenChannelAdapter$IntegrationMessageListener:73
```

We definitely should and can fix that inconsistency (thank you, Gary, for confirmation and issues), but it would be better to reproduce the issue and understand the root of cause.

CC @sobychacko

**Comment by sobychacko** [comment] 2016-07-15 18:57
Aretem/Gary - 

Here is a branch that I am working on for Kafka 0.9 binder upgrade: [This is a complete WIP branch, but i think would show the test failure]
https://github.com/sobychacko/spring-cloud-stream-binder-kafka/tree/kafka-0.9-upgrade

Please use `Spring Cloud Stream` from this PR from Marius before you build the above branch:  https://github.com/spring-cloud/spring-cloud-stream/pull/589

Once you build `SCS` from Marius's PR, come back to my branch and do the following:

`mvn clean test -Dtest=KafkaBinderTests#testDlqAndRetry`

this test would fail and you would see the stack trace that Gary was mentioning above.

**Comment by artembilan** [comment] 2016-07-15 19:29
After private discussion in Soby's commit we realized that some custom retry logic uses somehow regular `MessageListener`, although our one is always `IntegrationMessageListener`, which is `AcknowledgingMessageListener` anyway.
An immediate fix for their logic is to delegate to the `onMessage(message, null);`.

Anyway the `AbstractAdaptableMessageListener` must be fixed to propagate exception as is.

There is nothing to do with Spring Integration Kafka, so closing in favor of https://github.com/spring-projects/spring-kafka/issues/150

**Comment by garyrussell** [comment] 2016-07-16 07:45
>That said, the `IntegrationMessageListener` doesn't really need to extend the adapter - we can simply implement `AcknowledgingMessageListener`.

I think we should get rid of the overhead and simply implement. WDYT?

**Comment by artembilan** [comment] 2016-07-16 12:32
Well, looks like it would better to leave as is. We use there a `toMessagingMessage()` function from super. Although I guess we can copy/paste that `MessageConverter` usage, but my idea to do as less changes here as posible to decrease entropy level.
Particularly Soby's code relies on the fact that that our listener is in both roles. See their retry solution for binder consumer.
 WDYT?

**Comment by garyrussell** [comment] 2016-07-16 16:52
SCSt binder stuff should not do that - only the `AML` should be used - I'll need to take a look at their stuff next week.

**Comment by sobychacko** [comment] 2016-07-17 00:53
@garyrussell We use the `ConcurrentMessageListenerContainer` directly in the binder. How can we set the `retryTemplate` and `recoveryCallback` directly on the container? I didn't see a way they are exposed like that. They are provided through the `AbstractKafkaListenerContainerFactory`, but couldn't get a way to access it in the binder. Any suggestions?

**Comment by artembilan** [comment] 2016-07-17 01:19
Ha! Good catch @sobychacko !
I see your point. The logic is hidden here: https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java#L279.

This a part of `@KafkaListener` environment and we don't need that `RetryTemplate` hook in case of normal `ConcurrentMessageListenerContainer`, because we can simply inject `RetryingMessageListenerAdapter` on its own.
But since `IntegrationMessageListener` is something internal I think we don't have choice unless do logic copy/paste from that `AbstractKafkaListenerEndpoint` or move retry logic (or similar) to downstream on the `channel` of `KafkaMessageDrivenChannelAdapter`. E.g. something like `FixedSubscriberChannel` with `BridgeHandler` and `RequestHandlerRetryAdvice` on it.

Yes, we can expose `RetryTemplate` and `RecoveryCallback` on the `KafkaMessageDrivenChannelAdapter`, but won't be prone to copy/paste all the new feature in the SK into SIK?

**Comment by garyrussell** [comment] 2016-07-17 10:05
So the simple fix is to always wrap the original listener in an `AcknowledgingMessageListener` and call `onMessage(cr, null)` on the first branch.

However, you should probably use the `RetryingAcknowledgingMessageListenerAdapter` to wrap the original listener.

**Comment by garyrussell** [comment] 2016-07-17 10:06
We should consider some mechanism in SIK - i.e. if a `RetryTemplate` is injected into the adapter, automatically wrap the listener in a `RetryingAcknowledgingMessageListenerAdapter`.

**Comment by mbogoevici** [comment] 2016-07-17 16:06
@garyrussell +1

The current wrapping mechanism exists because in SI-K 1.3.1 there isn't any easy way to declaratively set up a retry advice around the message listener, but that shouldn't be the case on the long run.

**Comment by artembilan** [comment] 2016-07-20 17:09
Having such a discussion and may be a decision in the #125 to implement that, I think we can go ahead and add `RetryTemplate`, `RecoveryCallback` and `RecordFilterStrategy` properties into `KafkaMessageDrivenChannelAdapter` and wrap `IntegrationMessageListener` respectively.

We can address that even with this issue.

Anyway we can't provide XML attributes until the next minor version.

**Closed** 2016-07-21 21:26 UTC
Labels: bug, in pr
