### ISSUE TITLE
Invalid characters sent at the beginning of message

### ISSUE THREAD

**Issue by utmishra** [spring-projects/spring-integration-kafka#69] opened 2015-10-04 11:59 UTC
Using following code, I send Elasticsearch documents for indexing. I tried converting basic Objects to JSON and sent via producer. However, every message (as checked from the console) appends jibberish characters like - *��t�{"productId":2455*

	public boolean sendMessage()
	{
		PageRequest page = new PageRequest(0, 1); 
		Product p = product.findByName("Cream", page).getContent().get(0);
		String json = "";
		ObjectMapper mapper = new ObjectMapper();
		try {
			json = mapper.writeValueAsString(p);
		} catch (JsonProcessingException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}		
		logger.info("JSON = " + json);
		
		boolean status =  inputToKafka.send(org.springframework.integration.support.MessageBuilder.withPayload(json).build());
	    try {
	        Thread.sleep(10000);
	    } catch (InterruptedException e) {
	        e.printStackTrace();
	    }
	    return status;
	}

Outbound configuration

     <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:int="http://www.springframework.org/schema/integration"
           xmlns:int-kafka="http://www.springframework.org/schema/integration/kafka"
           xmlns:task="http://www.springframework.org/schema/task"
           xsi:schemaLocation="http://www.springframework.org/schema/integration/kafka http://www.springframework.org/schema/integration/kafka/spring-integration-kafka.xsd
    		http://www.springframework.org/schema/integration http://www.springframework.org/schema/integration/spring-integration.xsd
    		http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
    		http://www.springframework.org/schema/task http://www.springframework.org/schema/task/spring-task.xsd">
    
        <int:channel id="inputToKafka">
            <int:queue/>
        </int:channel>
    
        <int-kafka:outbound-channel-adapter
                id="kafkaOutboundChannelAdapter"
                kafka-producer-context-ref="kafkaProducerContext"
                channel="inputToKafka">
            <int:poller fixed-delay="1000" time-unit="MILLISECONDS" receive-timeout="0" task-executor="taskExecutor"/>
        </int-kafka:outbound-channel-adapter>
    
        <task:executor id="taskExecutor" pool-size="5" keep-alive="120" queue-capacity="500"/>
    
        <int-kafka:producer-context id="kafkaProducerContext">
            <int-kafka:producer-configurations>
                <int-kafka:producer-configuration broker-list="localhost:9092"
                                                  topic="shopo_topic"
                                                  compression-codec="default"/>
            </int-kafka:producer-configurations>
        </int-kafka:producer-context>
    
    	</beans>

Any clue ?

**Comment by artembilan** [comment] 2015-10-05 21:36
Hello, @utmishra !

Thank you for the attention to the project, first of all.

Let me ask you several question to help us to fix the issue (for you or for us).

1. Where exactly do you see those jibberish characters? On which part of your application? Just after the conversion to the JSON String or already on sending part? Or even receiving...
2. What Spring Integration Kafka version do you use? How about to switch to the latest one - `1.2.1`? 

From other side, I see that default value type is `B[`:
```
<xsd:attribute name="value-class-type" use="optional" type="xsd:string" default="[B">
```
So, try to configure `producer` with the `java.lang.String` and `StringEncoder`, of course!
I see that with the latest our version we can't configure it without `encoder/serializer`:
> Caused by: java.lang.IllegalArgumentException: Exactly one of 'value-serializer' or 'value-encoder' must be specified

So, be sure that you really have deal with proper `payload` types everywhere.

**Comment by artembilan** [comment] 2015-10-29 19:34
@utmishra,

we are going to release `1.3` soon and if there is really some issue we would like to address it there.
So, please, try to reach us ASAP with more info to reproduce or at least to play.

Otherwise we will be forced to close the ticket with the lack of feedback reason reason.

Thank you anyway !

**Comment by sharpnk** [comment] 2015-11-04 19:21
@artembilan Thanks for all the good work! Just curious, is there a set time frame for the release of 1.3? I couldn't find the release date info anywhere.

**Comment by kamrar** [comment] 2015-11-04 22:00
@artembilan I have the same issue with passing strings to kafka, during debuging in Serializer when I convert byte array to String I have ��t� in the begining of the String

**Comment by mbogoevici** [comment] 2015-11-04 22:42
Hi,

As pointed out by @abilan, this seems to be a mismatch between the serialization and deserialization strategies. Would you mind sharing your configuration for both publishing and consuming sides?

Thanks

**Comment by kamrar** [comment] 2015-11-04 22:56
done, I just used value-class-type="java.lang.String" and it is working.

**Comment by artembilan** [comment] 2015-11-04 23:00
Glad to hear! 
Closed as "Works as Designed" 
:smile:

**Closed by artembilan** 2015-11-04 23:00 UTC

**Comment by artembilan** [comment] 2015-11-06 00:03
After some debugging I see that issue is really around the String `payload` and value-class-type="[B".
Having that we end up on the code (`ProducerConfiguration`):
````java
return this.conversionService.convert(messagePayload, this.producerMetadata.getValueClassType());
````
which shows me in the debug this one:
```
java.lang.Object -> [B : org.springframework.core.serializer.support.SerializingConverter@25d3cfc8
```
So, according to the `ConversionService` state we are going to **serialize** `String`, but not invoke its `getByte()` method. 

Hope that explains the reason of those "invalid characters".
