### ISSUE TITLE
failed to shutdown tomcat

### ISSUE THREAD

**Issue by mbolgari** [spring-projects/spring-integration-kafka#97] opened 2015-12-22 14:14 UTC
Tomcat is not getting shut down when using spring-integration-kafka with message-driven-channel-adapter.
I used spring-integration-kafka-1.3.0, tomcat-8.0.30, kafka 0.8.2
Upon a shutdown request, I got a lot of "memory leak" warning and errors:

```
SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [si-kafka-shutdown] created a ThreadLocal with key of type [scala.util.DynamicVariable$$anon$1] (value [scala.util.DynamicVariable$$anon$1@280cb0ad]) and a value of type [scala.None$] (value [None]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [si-kafka-shutdown] created a ThreadLocal with key of type [scala.util.DynamicVariable$$anon$1] (value [scala.util.DynamicVariable$$anon$1@18a20278]) and a value of type [scala.Some] (value [Some([1.87] failure: end of input

{"jmx_port":-1,"timestamp":"1450784942805","host":"localhost","version":1,"port":9092}
                                                                                      ^)]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

See example project https://github.com/mbolgari/si-kafka-shutdown which also contains catalina.out.

**Comment by garyrussell** [comment] 2015-12-22 14:49
This appears to be a problem with Scala itself; a quick google of 
`"created a ThreadLocal with key of type [scala.util.DynamicVariable$$anon$1]"` 

returned lots of hits, including:

https://github.com/neo4j/neo4j/issues/1070
https://groups.google.com/forum/#!topic/scala-user/QuM4YKpGCvs

**Comment by mbolgari** [comment] 2015-12-23 08:36
I tried to implement some of the suggested solutions (workarounds), like clearing threadlocals.
But there is still a single thread which refuses to die
```
23-Dec-2015 10:25:19.153 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [si-kafka-shutdown] appears to have started a thread named [pool-3-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
 java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 reactor.jarjar.com.lmax.disruptor.LiteBlockingWaitStrategy.waitFor(LiteBlockingWaitStrategy.java:56)
 reactor.jarjar.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
 reactor.core.processor.RingBufferProcessor$BatchSignalProcessor.run(RingBufferProcessor.java:768)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
```
It seems that this thread is created in KafkaMessageListenerContainer:
```
this.messageDispatcher = new ConcurrentMessageListenerDispatcher(messageListener, errorHandler,
						Arrays.asList(partitions), offsetManager, concurrency, queueSize, dispatcherTaskExecutor,
						autoCommitOnError);
this.messageDispatcher.start();
```
To be more precise - here:
org.springframework.integration.kafka.listener.ConcurrentMessageListenerDispatcher
```
// start dispatchers
delegates.flip().keyBag().toSet().forEach(startDelegateProcedure);
```
Do you have any suggestions?
Thanks

**Comment by mbolgari** [comment] 2015-12-23 15:20
I was able to overcome the problem by wiring a dedicated ExecutorService (which sets daemon=true on threads) into KafkaMessageListenerContainer. Upon doing so, the tomcat shuts down gracefully.

**Comment by garyrussell** [comment] 2015-12-23 15:36
Thanks for the update; if you deploy the application context in tomcat via the normal Spring Web context, the context should shut down the executor, regardless of daemon threads, when the application is undeployed - Spring automatically closes the context.

If you are creating the context some other way, you need to close it yourself.

I have opened a [JIRA Issue](https://jira.spring.io/browse/INTEXT-214) to make sure we shut everything down properly.

**Comment by artembilan** [comment] 2018-07-30 13:49
The issue is not relevant any more...

**Closed by artembilan** 2018-07-30 13:49 UTC
